version: '2'
services:
  api:
    image: node:alpine
    volumes:
      - .:/home/app
    working_dir: /home/app
    ports:
      - 8081:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWD: root
      MYSQL_DB_NAME: moviesapi
      NODE_PORT: 80
    entrypoint:
      - npm
      - start
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./dump:/dump
    environment:
      MYSQL_ROOT_PASSWORD: root
